---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-7
  - name: fedora-27

suites:
  - name: default
    run_list:
      - recipe[crio::default]
      - recipe[test::resources]
    attributes:
      crio:
        network:
          - --enable-metrics
        conf:
          root: /var/lib/containers/storage
          runroot: /var/run/containers/storage
          storage_driver: overlay
          storage_option:
            - overlay.override_kernel_check=1
          api:
            listen: /var/run/crio/crio.sock
            stream_port: '10010'
            file_locking: true
          runtime:
            runtime: /usr/bin/runc
            default_workload_trust: trusted
            no_pivot: false
            conmon: /usr/libexec/crio/conmon
            conmon_env:
              - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
            selinux: false
            seccomp_profile: /etc/crio/seccomp.json
            apparmor_profile: crio-default
            cgroup_manager: cgroupfs
            hooks_dir_path: /usr/share/containers/oci/hooks.d
            pids_limit: 1024
            enable_shared_pid_namespace: false
            log_size_max: -1
          image:
            default_transport: docker://
            pause_image: kubernetes/pause
            pause_command: /pause
            image_volumes: mkdir
            registries:
              - docker.io
          network:
            network_dir: /etc/cni/net.d/
            plugin_dir: /usr/libexec/cni
