---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[crio::default]
      - recipe[test::resources]
    attributes:
      crio:
        network:
         - --enable-metrics
