sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-stable-precise
    packages:
      - chefdk

install: echo "skip bundle install"

before_script:
  - eval "$(chef shell-init bash)"

script:
  - chef --version
  - chef exec cookstyle --version
  - chef exec cookstyle
  - chef exec foodcritic --version
  - chef exec foodcritic . --exclude spec -f any -P
  - chef exec rspec
